package com.hlanz.bank.business.domain;
// Generated 14-may-2018 19:18:13 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuentas generated by hbm2java
 */
@Entity
@Table(name = "cuentas", catalog = "hlanz_bank")
public class Cuentas implements java.io.Serializable {

	private Integer idCuenta;
	private Usuarios usuarios;
	private String numero;
	private float saldo;
	private Set<Movimientos> movimientosesForCuentaEmisora = new HashSet<Movimientos>(0);
	private Set<Movimientos> movimientosesForCuentaReceptora = new HashSet<Movimientos>(0);

	public Cuentas() {
	}

	public Cuentas(Usuarios usuarios, String numero, float saldo) {
		this.usuarios = usuarios;
		this.numero = numero;
		this.saldo = saldo;
	}

	public Cuentas(Usuarios usuarios, String numero, float saldo, Set<Movimientos> movimientosesForCuentaEmisora,
			Set<Movimientos> movimientosesForCuentaReceptora) {
		this.usuarios = usuarios;
		this.numero = numero;
		this.saldo = saldo;
		this.movimientosesForCuentaEmisora = movimientosesForCuentaEmisora;
		this.movimientosesForCuentaReceptora = movimientosesForCuentaReceptora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cuenta", unique = true, nullable = false)
	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "propietario", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "numero", nullable = false, length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "saldo", nullable = false, precision = 12, scale = 0)
	public float getSaldo() {
		return this.saldo;
	}

	public void setSaldo(float saldo) {
		this.saldo = saldo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentasByCuentaEmisora")
	public Set<Movimientos> getMovimientosesForCuentaEmisora() {
		return this.movimientosesForCuentaEmisora;
	}

	public void setMovimientosesForCuentaEmisora(Set<Movimientos> movimientosesForCuentaEmisora) {
		this.movimientosesForCuentaEmisora = movimientosesForCuentaEmisora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentasByCuentaReceptora")
	public Set<Movimientos> getMovimientosesForCuentaReceptora() {
		return this.movimientosesForCuentaReceptora;
	}

	public void setMovimientosesForCuentaReceptora(Set<Movimientos> movimientosesForCuentaReceptora) {
		this.movimientosesForCuentaReceptora = movimientosesForCuentaReceptora;
	}

}
