package com.hlanz.bank.business.domain;
// Generated 02-jun-2018 23:39:42 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimientos generated by hbm2java
 */
@Entity
@Table(name = "movimientos", catalog = "hlanz_bank")
public class Movimientos implements java.io.Serializable {

	private Integer id;
	private Cuentas cuentasByCuentaEmisora;
	private Cuentas cuentasByCuentaReceptora;
	private Date fecha;
	private String concepto;
	private float movimiento;
	private float saldoActual;

	public Movimientos() {
	}

	public Movimientos(Cuentas cuentasByCuentaReceptora, Date fecha, String concepto, float movimiento,
			float saldoActual) {
		this.cuentasByCuentaReceptora = cuentasByCuentaReceptora;
		this.fecha = fecha;
		this.concepto = concepto;
		this.movimiento = movimiento;
		this.saldoActual = saldoActual;
	}

	public Movimientos(Cuentas cuentasByCuentaEmisora, Cuentas cuentasByCuentaReceptora, Date fecha, String concepto,
			float movimiento, float saldoActual) {
		this.cuentasByCuentaEmisora = cuentasByCuentaEmisora;
		this.cuentasByCuentaReceptora = cuentasByCuentaReceptora;
		this.fecha = fecha;
		this.concepto = concepto;
		this.movimiento = movimiento;
		this.saldoActual = saldoActual;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuenta_emisora")
	public Cuentas getCuentasByCuentaEmisora() {
		return this.cuentasByCuentaEmisora;
	}

	public void setCuentasByCuentaEmisora(Cuentas cuentasByCuentaEmisora) {
		this.cuentasByCuentaEmisora = cuentasByCuentaEmisora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuenta_receptora", nullable = false)
	public Cuentas getCuentasByCuentaReceptora() {
		return this.cuentasByCuentaReceptora;
	}

	public void setCuentasByCuentaReceptora(Cuentas cuentasByCuentaReceptora) {
		this.cuentasByCuentaReceptora = cuentasByCuentaReceptora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "concepto", nullable = false, length = 200)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "movimiento", nullable = false, precision = 12, scale = 0)
	public float getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(float movimiento) {
		this.movimiento = movimiento;
	}

	@Column(name = "saldo_actual", nullable = false, precision = 12, scale = 0)
	public float getSaldoActual() {
		return this.saldoActual;
	}

	public void setSaldoActual(float saldoActual) {
		this.saldoActual = saldoActual;
	}

}
