package com.hlanz.bank.business.domain;
// Generated 03-jun-2018 12:10:44 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PropiedadId generated by hbm2java
 */
@Embeddable
public class PropiedadId implements java.io.Serializable {

	private String nombre;
	private String valor;

	public PropiedadId() {
	}

	public PropiedadId(String nombre, String valor) {
		this.nombre = nombre;
		this.valor = valor;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "valor", length = 100)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PropiedadId))
			return false;
		PropiedadId castOther = (PropiedadId) other;

		return ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
				&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getValor() == castOther.getValor()) || (this.getValor() != null
						&& castOther.getValor() != null && this.getValor().equals(castOther.getValor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getValor() == null ? 0 : this.getValor().hashCode());
		return result;
	}

}
