package com.hlanz.bank.business.domain;
// Generated 03-jun-2018 12:10:44 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Propiedad generated by hbm2java
 */
@Entity
@Table(name = "propiedad", catalog = "hlanz_bank")
public class Propiedad implements java.io.Serializable {

	private PropiedadId id;

	public Propiedad() {
	}

	public Propiedad(PropiedadId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 100)),
			@AttributeOverride(name = "valor", column = @Column(name = "valor", length = 100)) })
	public PropiedadId getId() {
		return this.id;
	}

	public void setId(PropiedadId id) {
		this.id = id;
	}

}
