package com.hlanz.bank.business.domain;
// Generated 05-mar-2018 16:47:25 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuentas generated by hbm2java
 */
@Entity
@Table(name = "cuentas", catalog = "hlanz_bank")
public class Cuentas implements java.io.Serializable {

	private int idCuenta;
	private Usuarios usuarios;
	private String numero;
	private float saldo;
	private Set<Movimientos> movimientoses = new HashSet<Movimientos>(0);

	public Cuentas() {
	}

	public Cuentas(int idCuenta, Usuarios usuarios, String numero, float saldo) {
		this.idCuenta = idCuenta;
		this.usuarios = usuarios;
		this.numero = numero;
		this.saldo = saldo;
	}

	public Cuentas(int idCuenta, Usuarios usuarios, String numero, float saldo, Set<Movimientos> movimientoses) {
		this.idCuenta = idCuenta;
		this.usuarios = usuarios;
		this.numero = numero;
		this.saldo = saldo;
		this.movimientoses = movimientoses;
	}

	@Id

	@Column(name = "id_cuenta", unique = true, nullable = false)
	public int getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(int idCuenta) {
		this.idCuenta = idCuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "propietario", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "numero", nullable = false, length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "saldo", nullable = false, precision = 12, scale = 0)
	public float getSaldo() {
		return this.saldo;
	}

	public void setSaldo(float saldo) {
		this.saldo = saldo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentas")
	public Set<Movimientos> getMovimientoses() {
		return this.movimientoses;
	}

	public void setMovimientoses(Set<Movimientos> movimientoses) {
		this.movimientoses = movimientoses;
	}

}
