package com.hlanz.bank.business.domain;
// Generated 19-mar-2018 15:37:40 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Movimientos generated by hbm2java
 */
@Entity
@Table(name = "movimientos", catalog = "hlanz_bank")
public class Movimientos implements java.io.Serializable {

	private int id;
	private Cuentas cuentas;
	private String concepto;
	private float movimiento;
	private float saldoActual;

	public Movimientos() {
	}

	public Movimientos(int id, Cuentas cuentas, String concepto, float movimiento, float saldoActual) {
		this.id = id;
		this.cuentas = cuentas;
		this.concepto = concepto;
		this.movimiento = movimiento;
		this.saldoActual = saldoActual;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuenta", nullable = false)
	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	@Column(name = "concepto", nullable = false, length = 200)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "movimiento", nullable = false, precision = 12, scale = 0)
	public float getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(float movimiento) {
		this.movimiento = movimiento;
	}

	@Column(name = "saldo_actual", nullable = false, precision = 12, scale = 0)
	public float getSaldoActual() {
		return this.saldoActual;
	}

	public void setSaldoActual(float saldoActual) {
		this.saldoActual = saldoActual;
	}

}
